### ISSUE TITLE
Course-of-Action objects should have an appropriate external reference.

### ISSUE THREAD

**Issue by stmtstk** [mitre-attack/attack-website#286]
I found *course-of-action* objects in STIX 2.0 that I retrieve by TAXII protocol contain non-compliant *external reference* values.
For example, I found an *external reference* in a *course-of-action* object.

```
external_references": [
    {
        "source_name": "mitre-attack",
        "url": "https://attack.mitre.org/mitigations/T1156",
        "external_id": "T1156"
    }
]
```

I think the *external_id* should start with "M". Moreover, the URL is invalid (404 Not Found).

I recommend improving the two points below.

- *external_id* should be a mitigation ID that corresponds with a *course-of-action*
- URL should indicate a mitigation page.

This STIX file is in the below URL.
https://github.com/mitre-attack/attack-website/blob/master/data/stix/enterprise-attack.json

**Comment by isaisabel** [comment]
Hi @stmtstk,

Thank you for reaching out! The STIX data on this repo is a mirror of that on our [MITRE/CTI](https://github.com/mitre/cti) repository, which is the more relevant place to open such issues for the future (and also contains [additional documentation](https://github.com/mitre/cti/blob/master/USAGE.md) about the data model and methods for working with the STIX).

With regards to the course-of-action, that object (and other CoAs with such odd IDs) are leftovers from before the [ATT&CK version 5 release](https://attack.mitre.org/resources/updates/updates-july-2019/index.html) which changed the way mitigations are represented in ATT&CK. Prior to ATT&CK v5 such mitigations had a 1:1 relationship with techniques and as such shared their ATT&CK IDs [and lived on the same page as them](https://attack.mitre.org/versions/v4/techniques/T1156/), which is why the data looks like that for those old course-of-action objects.

Those course-of-actions are deprecated (marked with the `x_mitre_deprecated` field) to mark them as invalid for current versions of ATT&CK. We keep them in the data so as not to break any code which references them. Please see the USAGE document on MITRE/CTI [for more info on working with deprecated (and revoked) objects](https://github.com/mitre/cti/blob/master/USAGE.md#working-with-deprecated-and-revoked-objects).

**Comment by stmtstk** [comment]
Hi @isaisabel,

Thank you for your kind reply.
I missed a `x_mitre_deprecated` property.
I also understand before the ATT&CK version 5 dataset.
Your explanation is very helpful for me.

 Thank you again!
