### ISSUE TITLE
Add version information to previous_versions feature

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-website#34]
As a user of the ATT&CK website, I want to be able to know what version of the website and content is displayed on the previous versions pages.

Relies on https://github.com/mitre/cti/issues/66. See also #10.

**Comment by JasonKeirstead** [comment]
Just wanted to leave a comment - this feature is very important for folks building things around ATT&CK so that they can refer to the version that was used while they were building their product.... which also means that there always needs to be a link with a version number to whatever the current version is. Today, there is no such link which is problematic.

For example I can go to https://attack.mitre.org/previous/july2019/ and see the version from July-Oct 2019. However, I can't go to https://attack.mitre.org/previous/Dec2019 and see the *current* version that we're perhaps building something against and need to add a static link for.

**Comment by isaisabel** [comment]
I think to some extent this feature has been solved with the [versions of ATT&CK page](https://attack.mitre.org/resources/versions/) and improved banner marking. [mitre/cti#66](https://github.com/mitre/cti/issues/66) is still an ongoing project for marking the data with version numbers, but on the website it should be OK for now.
