### ISSUE TITLE
What changes in v3.6.0?

### ISSUE THREAD

**Issue by dickens88** [mitre-attack/attack-website#369]
Dear team,

I found there is a new release 7 days ago, the version is v3.6.0. when i clicked into the [release page](https://github.com/mitre-attack/attack-website/releases/tag/website-v3.6.0), the change log seems not changed. the latest version in the change log is still v3.5.0 which shown released at 7 January 2021. Maybe some one forgot to update the release? 
I also concern about #355 and #358 , but after i updated the master branch code, it seems the issues ware still there. thanks team.

**Comment by jondricek** [comment]
Thanks for the ping here - I had done `git push --tags` while forgetting to also `git push`. I just corrected that and the `master` branch should now have the fixes to the `CHANGELOG` as well as other fixes for the 3.6.0 release.

I will add however, that there are additional fixes that have been addressed that are not cleanly mentioned in the Changelog since we switched lead developers for this effort and I had not been tracking the Changelog as closely as I should have. If time permits I will go back and document the other fixes as well.
