### ISSUE TITLE
python3 update-attack.py returns: No module named 'drawSvg'

### ISSUE THREAD

**Issue by new-gen23** [mitre-attack/attack-website#407]
I followed the setup to install the website under linux (debian). However, when I come to the task to run `python3 update-attack.py`, the script returns: 

ModuleNotFoundError: No module named 'drawSvg'

Running `pip3 install drawSvg` returns:
`Requirement already satisfied: drawSvg in ./env/lib/python3.11/site-packages (2.1.1)`

Any idea, what is wrong?

**Comment by jondricek** [comment]
The website relies on our `mitreattack-python` library (https://github.com/mitre-attack/mitreattack-python) in order to fully build. `drawSvg` is a dependency over there that had a major update that broke our stuff. We addressed that in `mitreattack-python` last month in version 2.0.5, and now the latest is 2.0.6.

Over here for the website though, the master branch hasn't been updated yet to update the dependency, and is stuck on 1.7.2 for `mitreattack-python`. I'm fairly certain (but not 100% certain) that just updating to 2.0.6 would be just fine, but right now we are focusing hard on the upcoming release at the end of this month, at which point the website repo here will be fully updated and working again.

Hope that helps!
