### ISSUE TITLE
Roadmap not loading

### ISSUE THREAD

**Issue by DarbVS** [mitre-attack/attack-website#85]
https://attack.mitre.org/docs/attack_roadmap.pdf Is not loading (404 error).

**Comment by isaisabel** [comment]
Hi @DarbVS,

We recently reorganized some of our documents when we updated them for 2020. The new roadmap link is [here](https://attack.mitre.org/docs/attack_roadmap_2020.pdf).

Do you happen to know if there is a broken link pointing to the old URL? Our tests didn't detect any but it's possible they missed something.

**Comment by DarbVS** [comment]
Hi @isaisabel,

The first result on Google when searching “MITRE ATT&CKCON Techniques Data Sources”.

**Comment by DarbVS** [comment]
Hi @isaisabel,

The first result on Google when searching “MITRE ATT&CK Techniques Data Sources”.

**Comment by DarbVS** [comment]
Why the focus on only APT29? Have the Techniques Mapped to Data Sources been discontinued? If so, is there a similar product/replacement for the previous version?

**Comment by isaisabel** [comment]
Hi @DarbVS,

The old roadmap is still accessible at https://attack.mitre.org/docs/attack_roadmap_2019.pdf. The script used to generate the data for that visualization is available open-source [here](https://github.com/mitre-attack/attack-scripts/blob/master/scripts/techniques_data_sources_vis.py) as well.

We decided to focus on APT29 for the graphic this year because we wanted to include [the new mitigations we released last July](https://attack.mitre.org/resources/updates/updates-july-2019/index.html).
